cache:
  pip: true
  timeout: 1000

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      after_success:
        - poetry run codecov
    - python: 3.8
      dist: xenial

notifications:
  email: false

# repo branches to test
branches:
  - master

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry install
  - pip install -U git+https://github.com/sdss/clu

script:
  - poetry run pytest
